# Generated by Django 5.2.1 on 2025-05-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_reg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='email',
            field=models.EmailField(default='default@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
